<?php
/**
 * Title: 404
 * Slug: rundizstrap/hidden-404
 * Inserter: no
 *
 * @package rundizstrap
 * @since 0.0.1
 */
?>
<!-- wp:rundizstrap-companion/blocks-bs-container {"className":"container mt-0 d-flex flex-column flex-grow-1 flex-shrink-1"} -->
<div class="wp-block-rundizstrap-companion-blocks-bs-container page-404-container container mt-0 d-flex flex-column flex-grow-1 flex-shrink-1">
    <!-- wp:rundizstrap-companion/blocks-bs-row {"className":"flex-grow-1"} -->
    <div class="wp-block-rundizstrap-companion-blocks-bs-row row flex-grow-1">
        <!-- wp:rundizstrap-companion/blocks-bs-column {"tagName":"main","className":"col d-flex flex-column justify-content-center"} -->
        <main class="wp-block-rundizstrap-companion-blocks-bs-column site-main-column col d-flex flex-column justify-content-center">
            <!-- wp:rundizstrap-companion/blocks-bs-row {"className":"mb-1"} -->
            <div class="wp-block-rundizstrap-companion-blocks-bs-row row mb-1">
                <!-- wp:rundizstrap-companion/blocks-bs-column {"className":"col-8 offset-2 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4"} -->
                <div class="wp-block-rundizstrap-companion-blocks-bs-column col-8 offset-2 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
                    <!-- wp:image {"scale":"cover","sizeSlug":"full","linkDestination":"none"} -->
                    <figure class="wp-block-image size-full">
                        <img src="<?php echo esc_url(get_theme_file_uri('assets/imgs/404-cover-smoke-1200x290.webp')); ?>" 
                            alt="<?php echo esc_attr_x('Smoke floats past the screen.', 'image description', 'rundizstrap'); ?> 
                            <?php esc_attr_x('Image generated by ChatGPT.', 'image description', 'rundizstrap'); ?>" 
                            style="object-fit:cover"
                        />
                    </figure>
                    <!-- /wp:image -->
                </div>
                <!-- /wp:rundizstrap-companion/blocks-bs-row -->
            </div>
            <!-- /wp:rundizstrap-companion/blocks-bs-row -->

            <!-- wp:heading {"className":"display-1 mb-1","textAlign":"center","level":1} -->
            <h1 class="wp-block-heading has-text-align-center display-1 mb-1"><?php esc_html_e('Page not found', 'rundizstrap'); ?></h1>
            <!-- /wp:heading -->

            <!-- wp:paragraph {"className":"mb-1","style":{"typography":{"textAlign":"center"}}} -->
            <p class="has-text-align-center mb-1"><?php esc_html_e('It looks like the page you\'re looking for does not exists or has been moved.', 'rundizstrap'); ?></p>
            <!-- /wp:paragraph -->
            
            <!-- wp:group {"className":"text-center my-2","layout":{"type":"constrained"}} -->
            <div class="wp-block-group text-center my-2">
                <!-- wp:rundizstrap-companion/blocks-bs-button {"tagName":"a","textHtml":"<?php esc_html_e('Back to home page', 'rundizstrap'); ?>","href":"<?php echo esc_url(home_url('/')); ?>","className":"btn btn-outline-secondary"} -->
                <a class="wp-block-rundizstrap-companion-blocks-bs-button btn btn-outline-secondary" href="<?php echo esc_url(home_url('/')); ?>"><?php esc_html_e('Back to home page', 'rundizstrap'); ?></a>
                <!-- /wp:rundizstrap-companion/blocks-bs-button -->
            </div>
            <!-- /wp:group -->
        </main>
        <!-- /wp:rundizstrap-companion/blocks-bs-column -->
    </div>
    <!-- /wp:rundizstrap-companion/blocks-bs-row -->
</div>
<!-- /wp:rundizstrap-companion/blocks-bs-container -->